services:
  chef-mysql:
    image: mysql:8.0
    container_name: chef-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: chef_o2o
      TZ: Asia/Shanghai
    ports:
      - "3310:3306"
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - chef_mysql_data:/var/lib/mysql

volumes:
  chef_mysql_data: